language: node_js
node_js:
  - 12

branches:
  only:
  - gh-pages

services:
  - postgresql

before_script:
  - psql -c 'create database fruitbasket;' -U postgres
  - psql -c 'CREATE TABLE fruit_basket (id serial primary key, fruit text not null, quantity int not null, unit_price int not null);' -U postgres